### ISSUE TITLE
meta sepal when clicking on download TIF

### ISSUE THREAD

**Issue by yfinegold** [openforis/gfc_wrapper_python#29]
maybe just a one off experience but when i clicked on download TIF it made a sepal within a sepal 
![image](https://user-images.githubusercontent.com/5813936/144216341-3e7d03ea-49a7-487f-98c7-7a1705c1d96b.png)

**Comment by 12rambau** [comment]
that's what I call inception I love it, can you do it more than once?

Anyway I think it's related to  https://github.com/12rambau/sepal_ui/issues/311 which will be solved when sepal_ui 2.5.0 will be released (https://github.com/12rambau/sepal_ui/milestone/1)

**Comment by kdyson** [comment]
I have the same issue for the plot clip (beta) app! Thanks for working on this @12rambau .
